# Generated by Django 4.0.2 on 2022-04-18 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cuentas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinRepApp.empresa')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinRepApp.usuario')),
            ],
            options={
                'db_table': 'usuario_empresa',
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('saldoInicial', models.FloatField()),
                ('totalCargos', models.FloatField()),
                ('totalAbonos', models.FloatField()),
                ('saldoAcumulado', models.FloatField()),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinRepApp.cuentas')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.AddField(
            model_name='cuentas',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinRepApp.empresa'),
        ),
    ]
