# Generated by Django 4.0.2 on 2022-04-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0003_remove_movimientos_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='codigo',
            field=models.CharField(default='codigo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='fechaFinal',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='fechaInicio',
            field=models.DateField(default='2000-02-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='nombre',
            field=models.CharField(default='nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='saldoAcumulado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='saldoInicial',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='totalAbonos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='totalCargos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
