# Generated by Django 4.0.2 on 2022-04-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0004_movimientos_codigo_movimientos_fechafinal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='fechaFinal',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='saldoAcumulado',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='saldoInicial',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='totalAbonos',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='totalCargos',
        ),
    ]
