# Generated by Django 4.0.2 on 2022-04-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0006_movimientos_codigo_movimientos_fechafinal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='fechaFinal',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='fechaInicio',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='concepto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='referencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='totalAbonos',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='totalCargos',
            field=models.FloatField(null=True),
        ),
    ]
