# Generated by Django 4.0.2 on 2022-04-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0008_remove_movimientos_saldoacumulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='saldoInicial',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='totalAbonos',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='totalCargos',
        ),
    ]
