# Generated by Django 4.0.2 on 2022-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0009_remove_movimientos_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='codigo',
            field=models.CharField(default='codigo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='nombre',
            field=models.CharField(default='nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='concepto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='referencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='saldoInicial',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='totalCargos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='totalAbonos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
