# Generated by Django 4.0.2 on 2022-04-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0010_movimientos_codigo_movimientos_concepto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='totalAbonos',
            new_name='abonos',
        ),
        migrations.RenameField(
            model_name='movimientos',
            old_name='totalCargos',
            new_name='cargos',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
