# Generated by Django 4.0.2 on 2022-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0012_alter_movimientos_codigo_alter_movimientos_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='codigoAgrupador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='ingresoEgreso',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='nombreAgrupador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
