# Generated by Django 4.0.2 on 2022-05-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0013_movimientos_codigoagrupador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_Agrupadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinRepApp.empresa')),
            ],
            options={
                'db_table': 'codigos_agrupadores',
            },
        ),
    ]
