# Generated by Django 4.0.2 on 2022-05-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinRepApp', '0014_codigos_agrupadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigos_agrupadores',
            name='nombre',
            field=models.CharField(default='Pedro', max_length=100),
            preserve_default=False,
        ),
    ]
